# Extra autostart processes
# exec-once = uwsm-app -- my-service
# --- Wallpaper Settings ---
# 1. Sweep up any zombie sockets from a crash, then start the daemon fresh
# --- Wallpaper Settings ---
# 1. Wrap the cleanup and daemon in bash so Hyprland understands it
exec-once = bash -c "rm -f /run/user/1000/*awww*.sock && awww-daemon"

# 2. Add a 2-second delay to the slideshow so the daemon is fully awake first!
exec-once = bash -c "sleep 2 && ~/.config/hypr/scripts/wallpaper_slideshow.sh"


#Lockscreen = yes
exec-once = hyprlock
exec-once = hypridle
exec-once = sleep 2 &&  killall swaybg
