# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
indd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

# Fix Brightness
bindel = , XF86MonBrightnessUp, exec, brightnessctl --device=intel_backlight set +5%
# UPDATED Brightness down (prevent balckout at 30%)
bindel = , XF86MonBrightnessDown, exec, brightnessctl --device=intel_backlight set 5%- --min-value=20
# Super n to get or remove the waybar
bind = SUPER, N, exec, pkill -SIGUSR1 waybar

# Precision Brightness (1% steps)
bindel = SUPER ALT, XF86MonBrightnessUp, exec, brightnessctl --device=intel_backlight set +1%
bindel = SUPER ALT, XF86MonBrightnessDown, exec, brightnessctl --device=intel_backlight set 1%- --min-value=20

# Override Volume to 1% steps (using SwayOSD)
bindel = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume +1
bindel = , XF86AudioLowerVolume, exec, swayosd-client --output-volume -1


# Make Super+Alt+W change the wallpaper
bind = SUPER ALT, W, exec, ~/.config/hypr/scripts/wallpaper_slideshow.sh

bind = $mainMod ALT, W, exec, ~/.config/hypr/scripts/wall-picker.sh

# browser with the sloppy key
bind = , XF86Launch7, exec, kitty -e btop

# mouse toggle workspace
bind = , mouse:275, workspace, e+1
 
# special workspace through forward click 
bind = , mouse:276, togglespecialworkspace, scratchpad
